/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Interface.ProductListener;
import Utility.OrderItem;
import Utility.ProductButton;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import model.ItemModel;
import model.OrderItemModel;

/**
 *
 * @author Visak
 */
public class OrderPanel extends javax.swing.JPanel {

    private ItemModel foodCategoryType;
    private OrderItemModel foodItems;
    private OrderItemModel foodOrdered;
    
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        //Model class to store the item data
        foodCategoryType = new ItemModel();
        foodItems = new OrderItemModel();
        foodOrdered = new OrderItemModel();
        
        JPanel content = new JPanel();
        ProductButton buttonData[] = new ProductButton[5];
        ButtonHandler handler=new ButtonHandler();
        
        for(int index = 0; index < 5; index++){
            buttonData[index] = new ProductButton("Welcome to hell ", index);
            buttonData[index].addProductListener(new ProductListener() {
                @Override
                public void clickedProducts(int i) {
                    System.out.println(i);
                }
            });
            
            content.add(buttonData[index]);
        }
        sp_category.getViewport().setView(content);
        
        JPanel contentOrderItem = new JPanel();
        contentOrderItem.setLayout(new GridLayout(0,4));
        ProductButton buttonOrderItem[] = new ProductButton[100];
        
        for(int index = 0; index < 100; index++){
           buttonOrderItem[index] = new ProductButton("Welcome to hell ", index);
           contentOrderItem.add(buttonOrderItem[index]);
        }
        sp_product_list.getViewport().setView(contentOrderItem);
        
        
        JPanel contentOrder = new JPanel();
        contentOrder.setLayout(new BoxLayout(contentOrder, BoxLayout.Y_AXIS));
        OrderItem orderData[] = new OrderItem[10];
        for(int index = 0; index < 10; index++){
            orderData[index] = new OrderItem(); 
            contentOrder.add(orderData[index]);
        }
        sp_detail_list.getViewport().setView(contentOrder);
        
        
        
    }

    public class ButtonHandler implements ProductListener{   

    //This method is called in case an action event occurs.For example you click on the
    //button      
     public void actionPerformed(ActionEvent event){

         // gets the name of the button and displays in the label.
         ProductButton btn = (ProductButton) event.getSource();
         System.out.println(btn.getAction());

     }       

        @Override
        public void clickedProducts(int i) {
            System.out.println(i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        sp_detail_list = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sp_category = new javax.swing.JScrollPane();
        sp_product_list = new javax.swing.JScrollPane();

        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 0));
        jPanel4.setLayout(new java.awt.BorderLayout());

        sp_detail_list.setBackground(new java.awt.Color(255, 0, 255));
        sp_detail_list.setBorder(null);
        sp_detail_list.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jPanel4.add(sp_detail_list, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 0));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        sp_category.setBackground(new java.awt.Color(255, 102, 102));
        sp_category.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        sp_product_list.setBackground(new java.awt.Color(0, 255, 51));
        sp_product_list.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_product_list)
            .addComponent(sp_category, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sp_category, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sp_product_list, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane sp_category;
    private javax.swing.JScrollPane sp_detail_list;
    private javax.swing.JScrollPane sp_product_list;
    // End of variables declaration//GEN-END:variables
}

