/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author priyesh
 */
public class SettingsPanel extends javax.swing.JPanel {

    private JPanel visiblePanel;
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        FoodTypePanel panels = new FoodTypePanel();
        visiblePanel = panels;
        setMainLayout(panels, panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodType = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        foodCategory = new javax.swing.JButton();
        foodMeat = new javax.swing.JButton();
        shop = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        foodType.setBackground(new java.awt.Color(0, 153, 255));
        foodType.setText("Food Type");
        foodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodTypeActionPerformed(evt);
            }
        });

        staff.setText("Staff");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });

        foodCategory.setBackground(new java.awt.Color(0, 102, 255));
        foodCategory.setText("Food Category");
        foodCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCategoryActionPerformed(evt);
            }
        });

        foodMeat.setText("Food Meat");
        foodMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodMeatActionPerformed(evt);
            }
        });

        shop.setText("Shop");
        shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopActionPerformed(evt);
            }
        });

        panel.setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foodType, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(foodCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foodMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shop, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodTypeActionPerformed
        // TODO add your handling code here:
         if(visiblePanel != null)
            removeMainLayout(visiblePanel, panel);
          FoodTypePanel panels = new FoodTypePanel();
        setMainLayout(panels,panel);
    }//GEN-LAST:event_foodTypeActionPerformed

    private void foodCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCategoryActionPerformed
        // TODO add your handling code here:
         if(visiblePanel != null)
            removeMainLayout(visiblePanel, panel);
          FoodCategory panels = new FoodCategory();
        setMainLayout(panels,panel);
    }//GEN-LAST:event_foodCategoryActionPerformed

    private void shopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopActionPerformed
        // TODO add your handling code here:\
         if(visiblePanel != null)
            removeMainLayout(visiblePanel, panel);
          ShopeDetails panels = new ShopeDetails();
        setMainLayout(panels,panel);
    }//GEN-LAST:event_shopActionPerformed

    private void foodMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodMeatActionPerformed
        // TODO add your handling code here:
         if(visiblePanel != null)
            removeMainLayout(visiblePanel, panel);
         FoodMeatType panels = new FoodMeatType();
        setMainLayout(panels,panel);
    }//GEN-LAST:event_foodMeatActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
         if(visiblePanel != null)
            removeMainLayout(visiblePanel, panel);
        StaffPanel panels = new StaffPanel();
        setMainLayout(panels,panel);
    }//GEN-LAST:event_staffActionPerformed

    private void setMainLayout(JPanel toAddPanel, JPanel mainPanel) {
        toAddPanel.setVisible(true);
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(toAddPanel);
        mainPanel.validate();
    }
    
    private void removeMainLayout(JPanel toAddPanel, JPanel mainPanel) {
        mainPanel.removeAll();
        mainPanel.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foodCategory;
    private javax.swing.JButton foodMeat;
    private javax.swing.JButton foodType;
    private javax.swing.JPanel panel;
    private javax.swing.JButton shop;
    private javax.swing.JButton staff;
    // End of variables declaration//GEN-END:variables
}
