/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Services.ShopdetailsService;
import Utility.ButtonColumn;
import Utility.Utility;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ShopDetailsModel;

/**
 *
 * @author priyesh
 */
public class ShopeDetails extends javax.swing.JPanel {

    /**
     * Creates new form ShopeDetails
     */
    public ShopeDetails() {
        initComponents();
        getAllShops();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shopName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        addShop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shopTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        shopTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add Shop Details"));
        setPreferredSize(new java.awt.Dimension(1650, 1080));

        shopName.setToolTipText("Food Type Name");

        jLabel2.setText("Shop Name*");

        phone.setToolTipText("Food Type Name");

        jLabel3.setText("Phone Number*");

        place.setToolTipText("Food Type Name");

        jLabel4.setText("Place*");

        jLabel5.setText("Address*");

        email.setToolTipText("Food Type Name");

        jLabel6.setText("Email*");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        addShop.setBackground(new java.awt.Color(0, 153, 255));
        addShop.setForeground(new java.awt.Color(255, 255, 255));
        addShop.setText("Create");
        addShop.setName("LoginBtn"); // NOI18N
        addShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShopActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Shop Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        shopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sl. No.", "Shop Name", "Phone Number", "Email", "Place", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(shopTable);

        shopTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sl. No.", "Shop Name", "Phone Number", "Email", "Place", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(shopTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shopName)
                    .addComponent(place)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addShop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addShop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShopActionPerformed
        // TODO add your handling code here:
        // validation for empty
        if (Utility.isNullOrEmpty(shopName.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Name Cannot be Empty.", "ERROR", 0);
            return;
        }

        if (Utility.isNullOrEmpty(phone.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Mobile Cannot be Empty.", "ERROR", 0);
            return;
        }

        if (Utility.isNullOrEmpty(email.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Email Address Cannot be Empty.", "ERROR", 0);
            return;
        }

        if (Utility.isNullOrEmpty(place.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Password Cannot be Empty.", "ERROR", 0);
            return;
        }

        if (Utility.isNullOrEmpty(address.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Address Cannot be Empty.", "ERROR", 0);
            return;
        }
        if (!Utility.validatePhone(phone.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Please enter valid phone number", "ERROR", 0);
            return;
        }

        if (!Utility.validateEmailAddress(email.getText().toString().trim().toString())) {
            JOptionPane.showMessageDialog(null, "Please enter valid Email Address.", "ERROR", 0);
            return;
        }
        ShopDetailsModel shop = new ShopDetailsModel();
        shop.setShop_name(shopName.getText().toString());
        shop.setPhone_no(phone.getText().toString());
        shop.setEmail_address(email.getText().toString());
        shop.setPlace(place.getText().toString());
        shop.setAddress(address.getText().toString());

        ShopdetailsService shopdetailsService = new ShopdetailsService();
        int response;
        if (addShop.getText().contains("Update")) {
            shop.setShop_id(shopId);
            response = shopdetailsService.saveOrUpdatehopdetails(shop, false);
        } else {
            response = shopdetailsService.saveOrUpdatehopdetails(shop, true);
        }
        clearAll();
        if (response == 1) {
            getAllShops();
            JOptionPane.showMessageDialog(null, "Staff " + shop.getShop_name() + " has been updated successfully", "Success", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid", "ERROR", 0);
        }
    }//GEN-LAST:event_addShopActionPerformed
    public void getAllShops() {
        ShopdetailsService shopdetailsService = new ShopdetailsService();
        List<ShopDetailsModel> shopList = shopdetailsService.getAllShops();

        String data[][] = new String[shopList.size()][8];
        for (int i = 0; i < shopList.size(); i++) {
            data[i][0] = new Integer(i + 1).toString();
            data[i][1] = shopList.get(i).getShop_name();
            data[i][2] = shopList.get(i).getPhone_no();
            data[i][3] = shopList.get(i).getEmail_address();
            data[i][4] = shopList.get(i).getPlace();
            data[i][5] = shopList.get(i).getAddress();
            data[i][6] = "Edit";
            data[i][7] = "Delete";
        }
        String columnNames[] = new String[]{"Sl.No.", "Shop Name", "Phone", "Email", "Place", "Address", "", ""};
        DefaultTableModel tbl = new DefaultTableModel(data, columnNames);
        shopTable.setModel(tbl);

        Action update = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                String idValString = (String) ((DefaultTableModel) table.getModel()).getValueAt(modelRow, 0);
                int idVal = Integer.parseInt(idValString);
                editField(shopList.get(idVal - 1));
            }

            private void editField(ShopDetailsModel staffModel) {
                shopId = staffModel.getShop_id();
                ShopdetailsService shopdetailsService = new ShopdetailsService();
                shopName.setText(staffModel.getShop_name());
                phone.setText(staffModel.getPhone_no());
                email.setText(staffModel.getEmail_address());
                place.setText(staffModel.getPlace());
                address.setText(staffModel.getAddress());
                addShop.setText("Update");
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };

        Action delete = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                String id = (String) ((DefaultTableModel) table.getModel()).getValueAt(modelRow, 0);
                int shopId = shopList.get(Integer.parseInt(id) - 1).getShop_id();

                int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm Deactivation ?", "Warning", JOptionPane.YES_NO_OPTION);
                int status = 0;
                if (dialogResult == JOptionPane.YES_OPTION) {
                    status = shopdetailsService.deleteFoodItem(shopId);
                }

                if (status == 1) {
                    clearAll();
                    getAllShops();
                }

            }
        };

        ButtonColumn buttonColumnEdit = new ButtonColumn(shopTable, update, 6);
        buttonColumnEdit.setMnemonic(KeyEvent.VK_D);
        ButtonColumn buttonColumnDelete = new ButtonColumn(shopTable, delete, 7);
        buttonColumnDelete.setMnemonic(KeyEvent.VK_D);
    }

    private int shopId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addShop;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField place;
    private javax.swing.JTextField shopName;
    private javax.swing.JTable shopTable;
    private javax.swing.JTable shopTable1;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        shopName.setText("");
        phone.setText("");
        place.setText("");
        address.setText("");
        email.setText("");
        addShop.setText("Create");
    }

}
